### ISSUE TITLE
Improperly encoded XML

### ISSUE THREAD

**Issue by iandees** [iandees/poism-py#19]
Got an error while trying to save a change for a place with an accent in a tag:

```
[2023-04-14 02:29:31,098] INFO in server: Applying change: <osmChange version="0.6" generator="poism"><modify><node id="5286895028" version="4" lat="44.9302409" lon="-93.2888324" changeset="134883553"><tag k="addr:city" v="Minneapolis" /><tag k="addr:housenumber" v="4000" /><tag k="addr:postcode" v="55409" /><tag k="addr:state" v="MN" /><tag k="addr:street" v="Lyndale Avenue South" /><tag k="amenity" v="restaurant" /><tag k="cuisine" v="laotian" /><tag k="name" v="Khâluna" /><tag k="phone" v="+16123455199" /><tag k="website" v="https://khaluna.com/" /><tag k="opening_hours" v="Mo-Su 16:00-22:00; Sa-Su 10:00-14:00" /></node></modify></osmChange>
[2023-04-14 02:29:31,377] INFO in server: Response from changeset upload: Document not well-formed.
Line 1, column 413 (fatal):
Input is not proper UTF-8, indicate encoding !
Bytes: 0xE2 0x6C 0x75 0x6E
[2023-04-14 02:29:31,378] ERROR in app: Exception on /edit/node/5286895028 [POST]
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 563, in edit_object
    apply_change(new_obj, 'modify', changeset_id)
  File "/app/server.py", line 271, in apply_change
    resp.raise_for_status()
  File "/app/.heroku/python/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

**Comment by iandees** [comment]
Trying to specify encoding in ElementTree.tostring with 579ef6f.

**Comment by iandees** [comment]
Looks like it worked.
